// expos-data.js — liste des expositions, partagée par expositions.html (ligne du temps)
// et galeries.html (« 4 expositions ici depuis 2005 »).
// type : "solo" (personnelle), "group" (collective), "salon" (salon / art fair)
window.EXPOS = [
  { year: 2019, title: "Galerie Bouillon d’Art", city: "Bordeaux", country: "France", type: "solo" },
  { year: 2018, title: "Artclub Gallery", city: "Paris", country: "France", type: "solo" },
  { year: 2015, title: "Galerie Next", city: "Toulouse", country: "France", type: "solo" },
  { year: 2013, title: "Galerie Salvany", city: "Clermont-Ferrand", country: "France", type: "solo" },
  { year: 2012, title: "Artclub Gallery", city: "Paris", country: "France", type: "solo" },
  { year: 2011, title: "Palm Beach", city: "Cannes", country: "France", type: "solo" },
  { year: 2011, title: "Galerie Neel", city: "Cannes", country: "France", type: "solo" },
  { year: 2010, title: "Galerie des Chapelains", city: "Nevers", country: "France", type: "solo" },
  { year: 2009, title: "Artclub Gallery", city: "Paris", country: "France", type: "solo" },
  { year: 2006, title: "Galerie Salvany", city: "Clermont-Ferrand", country: "France", type: "solo" },
  { year: 2005, title: "Artclub Gallery", city: "Paris", country: "France", type: "solo" },
  { year: 2005, title: "Galerie Futurart", city: "Bruxelles", country: "Belgique", type: "solo" },
  { year: 2002, title: "Galerie Aktuaryus", city: "Strasbourg", country: "France", type: "solo" },
  { year: 2002, title: "Galerie des Chapelains", city: "Nevers", country: "France", type: "solo" },
  { year: 2001, title: "Galerie Tosaka", city: "Paris", country: "France", type: "solo" },
  { year: 2000, title: "Galerie Aktuaryus", city: "Strasbourg", country: "France", type: "solo" },
  { year: 2000, title: "Galerie des Chapelains", city: "Nevers", country: "France", type: "solo" },
  { year: 1997, title: "Galerie Saint-Cyr", city: "Nevers", country: "France", type: "solo" },
  { year: 1996, title: "Galerie Étienne De Caussans", city: "Paris", country: "France", type: "solo" },
  { year: 1993, title: "Galerie Jason", city: "Perpignan", country: "France", type: "solo" },

  { year: 2024, title: "French Art Network — Galerie Rue Toulouse", city: "Laguna Beach, Carmel", country: "États-Unis", type: "group" },
  { year: 2024, title: "Galerie Page", city: "Biarritz", country: "France", type: "group" },
  { year: 2018, title: "Galerie ArtAddict", city: "Mougins", country: "France", type: "group" },
  { year: 2018, title: "Art3F", city: "Cannes", country: "France", type: "salon" },
  { year: 2017, title: "ArtShopping", city: "Paris", country: "France", type: "salon" },
  { year: 2017, title: "ArtFair", city: "Lausanne", country: "Suisse", type: "salon" },
  { year: 2017, title: "Art3F", city: "Paris", country: "France", type: "salon" },
  { year: 2016, title: "Exposition ArtFair", city: "Anvers", country: "Belgique", type: "salon" },
  { year: 2010, title: "Galerie Neel", city: "Cannes", country: "France", type: "group" },
  { year: 2008, title: "Galerie Joël Dupuis", city: "Hardelot-sur-Mer", country: "France", type: "group" },
  { year: 2007, title: "The Catto Gallery", city: "Londres", country: "Angleterre", type: "group" },
  { year: 2007, title: "Galerie Joël Dupuis", city: "Hardelot-sur-Mer", country: "France", type: "group" },
  { year: 2007, title: "Galerie Hugues Penot", city: "La Baule", country: "France", type: "group" },
  { year: 1998, title: "Artexpo", city: "New York", country: "États-Unis", type: "salon" },
  { year: 1998, title: "Galerie Christian Dazy", city: "Dijon", country: "France", type: "group" },
  { year: 1997, title: "Musée de Marzy", city: "Marzy", country: "France", type: "group" },
  { year: 1996, title: "Salon de Printemps", city: "Decize", country: "France", type: "salon" },
  { year: 1994, title: "Salon de Bourges", city: "Bourges", country: "France", type: "salon" },
  { year: 1993, title: "Salon d’Automne (Grand Palais)", city: "Paris", country: "France", type: "salon" },
  { year: 1992, title: "Exposition d’Été", city: "Decize", country: "France", type: "group" }
];

// Position des villes (vue carte de la page Expositions). Une ville ajoutée ci-dessus
// sans position ici n'apparaît simplement pas sur la carte.
window.EXPO_CITIES = {
  "Bordeaux": [44.8378, -0.5792],
  "Paris": [48.8566, 2.3522],
  "Toulouse": [43.6047, 1.4442],
  "Clermont-Ferrand": [45.7772, 3.0870],
  "Cannes": [43.5528, 7.0174],
  "Nevers": [46.9896, 3.1590],
  "Bruxelles": [50.8503, 4.3517],
  "Strasbourg": [48.5734, 7.7521],
  "Perpignan": [42.6887, 2.8948],
  "Laguna Beach, Carmel": [33.5427, -117.7854],
  "Biarritz": [43.4832, -1.5586],
  "Mougins": [43.6000, 6.9950],
  "Lausanne": [46.5197, 6.6323],
  "Anvers": [51.2194, 4.4025],
  "Hardelot-sur-Mer": [50.6360, 1.5830],
  "Londres": [51.5074, -0.1278],
  "La Baule": [47.2863, -2.3920],
  "New York": [40.7128, -74.0060],
  "Dijon": [47.3220, 5.0415],
  "Marzy": [46.9811, 3.0931],
  "Decize": [46.8283, 3.4611],
  "Bourges": [47.0810, 2.3988],
};
